# Generated by Django 6.0.5 on 2026-05-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='policy_id',
            new_name='policy',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_agent_i_d1e98e_idx',
            old_name='notificatio_agent_i_b82916_idx',
        ),
    ]
